spring:

  datasource:
    url: jdbc:mysql://localhost:3306/shop?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  thymeleaf:
    cache: false

  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true

itemImgLocation: C:/shop/item

uploadPath: file:///C:/shop/

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
